# BN-LINK BNC-60/U133TJ power monitoring outlet switch
substitutions:
  name: bnlink-outlet
  friendly_name: BN-Link Outlet
  voltage_divider: "798.9"
  current_resistor: "0.003513"
  current_multiply: "2.0"

packages:
  deviceinfo: !include common/deviceinfo.yaml
  factoryreset: !include common/factoryreset.yaml

dashboard_import:
  package_import_url: github://jimparis/esphome-cfg/bnlink-outlet.yaml@main

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jim.bnlink-outlet
    version: "1.0"

  on_boot:
    priority: 300
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - light.turn_off: wifi_status

esp8266:
  restore_from_flash: true
  board: esp01_1m

logger:
  baud_rate: 0 # No UART connected

ota:
  - platform: esphome

api:

time:
  - platform: homeassistant
    id: homeassistant_time

external_components:
  - source:
      type: git
      url: https://github.com/jimparis/esphome-cfg
    refresh: 1s

preferences:
  flash_write_interval: 300s

wifi:
  ap:

captive_portal:

binary_sensor:
  - pin:
      number: GPIO3
      inverted: true
    id: !extend main_button
    name: ${name} Button
    on_press:
      - switch.toggle: relay_switch

output:
  - platform: esp8266_pwm
    id: blue_led
    pin:
      number: GPIO1
      inverted: true
  - platform: esp8266_pwm
    id: red_led
    pin:
      number: GPIO13
      inverted: true

switch:
  - platform: gpio
    name: ${name} Relay
    id: relay_switch
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: relay_status
    on_turn_off:
      - light.turn_off: relay_status

light:
  - platform: monochromatic
    id: wifi_status
    output: red_led
    default_transition_length: 50ms
  - platform: monochromatic
    id: relay_status
    output: blue_led
    default_transition_length: 50ms

sensor:
  - platform: hlw8012
    sel_pin:
      number: GPIO12
      inverted: True
    cf_pin: GPIO4
    cf1_pin: GPIO5
    current_resistor: ${current_resistor}
    voltage_divider: ${voltage_divider}
    current:
      name: "${name} Current"
      unit_of_measurement: A
      filters:
        - multiply: ${current_multiply}
        - or:
            - throttle: 60s
            - delta: 0.5
    voltage:
      name: "${name} Voltage"
      unit_of_measurement: V
      filters:
        - or:
            - throttle: 300s
            - delta: 5.0
    power:
      id: "sensed_power"
      name: "${name} Power"
      unit_of_measurement: W
      filters:
        - or:
            - throttle: 60s
            - delta: 25.0
    change_mode_every: 6
    update_interval: 3s

  - platform: total_daily_energy
    name: "${name} Total Daily Energy"
    power_id: "sensed_power"
    filters:
        - multiply: 0.001 # W to kW
    unit_of_measurement: kWh
