substitutions:
  name: elegrp-spn30
  friendly_name: ELEGRP Switch
  traveler_hot_hold_ms: "250"

packages:
  deviceinfo: !include common/deviceinfo.yaml
  factoryreset: !include common/factoryreset.yaml

dashboard_import:
  # Limited to 44 chars, see https://github.com/esphome/esphome/issues/11281
  #                   12345678901234567890123456789012345678901234
  package_import_url: github://jimparis/esphome-cfg/ele-spn30.yaml

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jim.elegrp-spn30
    version: "1.0"

  # https://github.com/libretiny-eu/libretiny/issues/316
  platformio_options:
    build_flags:
      - -DLWIP_DHCP_DOES_ACD_CHECK=0

bk72xx:
  board: cb2s

factory_reset:
  resets_required: 10
  max_delay: 10s

# Support logging, but not to UART
logger:
  baud_rate: 0
  level: DEBUG
  logs:
    binary_sensor: WARN

api:

ota:
  - platform: esphome

external_components:
  - source:
      type: git
      url: https://github.com/jimparis/esphome-cfg
    refresh: 1s

preferences:
  flash_write_interval: 300s

globals:
  - id: traveler_last_edge
    type: uint32_t
    initial_value: '0'

wifi:
  ap:

captive_portal:


# P23: off button (needs pullup)
# P6:  on button (needs pullup)
# P7:  relay (high = closed)
# P8:  traveler sense (needs pullup, toggle when 120V present?)
# P24: LED (active low)

binary_sensor:
  - platform: gpio
    pin:
      number: P6
      mode: INPUT_PULLUP
      inverted: true
    name: "Up Button"
    internal: true
    on_press:
      - light.turn_on: relay_light
      - logger.log:
          level: DEBUG
          format: "Up button pressed -> Relay ON"

  - platform: gpio
    pin:
      number: P23
      mode: INPUT_PULLUP
      inverted: true
    id: !extend main_button
    name: "Down Button"
    internal: true
    on_press:
      - light.turn_off: relay_light
      - logger.log:
          level: DEBUG
          format: "Down button pressed -> Relay OFF"

  - platform: gpio
    pin:
      number: P8
      mode: INPUT_PULLUP
    id: traveler_raw
    internal: true
    on_press:
      - lambda: |-
          id(traveler_last_edge) = esphome::millis();
    on_release:
      - lambda: |-
          id(traveler_last_edge) = esphome::millis();

  - platform: template
    id: traveler_detected
    name: "Traveler Detected"
    device_class: power
    on_press:
      - light.toggle: relay_light
      - logger.log:
          level: DEBUG
          format: "Traveler detected -> toggling relay"
    on_release:
      - light.toggle: relay_light
      - logger.log:
          level: DEBUG
          format: "Traveler cleared -> toggling relay"
output:
  - platform: gpio
    id: relay_output
    pin: P7

  - platform: gpio
    id: led_output
    pin:
      number: P24
      inverted: true

light:
  - platform: binary
    id: relay_light
    name: "Relay"
    output: relay_output
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: wifi_status
    on_turn_off:
      - light.turn_off: wifi_status

  - platform: status_led
    id: wifi_status
    name: "Status LED"
    output: led_output
    restore_mode: ALWAYS_OFF

# if we see any edge on the traveler pin recently assume the traveler
# line is hot.  In theory this should happen at 60 Hz, but in practice
# we can have long delays due to polling patterns, internal flash
# writes, etc.  Having a longer delay in practice doesn't feel too
# laggy.
interval:
  - interval: 50ms
    then:
      - lambda: |-
          const bool state = (esphome::millis() - id(traveler_last_edge)) < ${traveler_hot_hold_ms};
          id(traveler_detected).publish_state(state);
