substitutions:
  name: gosund-switch
  friendly_name: Gosund Switch

packages:
  deviceinfo: !include common/deviceinfo.yaml
  factoryreset: !include common/factoryreset.yaml

dashboard_import:
  package_import_url: github://jimparis/esphome-cfg/gosund-switch.yaml@main

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jim.gosund-switch
    version: "1.0"

  on_boot:
    priority: 300
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - light.turn_off: wifi_status

esp8266:
  restore_from_flash: true
  board: esp8285

logger:

api:

ota:
  - platform: esphome

external_components:
  - source:
      type: git
      url: https://github.com/jimparis/esphome-cfg
    refresh: 1s

preferences:
  flash_write_interval: 300s

wifi:
  ap:

captive_portal:

button:
  - platform: restart
    id: gosund_restart
  - platform: factory_reset
    id: gosund_factory_reset

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    id: !extend main_button
    on_press:
      - switch.toggle: gosund_switch

output:
  - platform: esp8266_pwm
    id: green_led
    pin:
      number: GPIO02
      inverted: true
  - platform: esp8266_pwm
    id: red_led
    pin:
      number: GPIO16
      inverted: true

switch:
  - platform: gpio
    name: Relay
    id: gosund_switch
    pin: GPIO14
    restore_mode: RESTORE_DEFAULT_OFF
    on_turn_on:
      - light.turn_on: gosund_relay_status
    on_turn_off:
      - light.turn_off: gosund_relay_status

light:
  - platform: monochromatic
    id: wifi_status
    output: green_led
    default_transition_length: 50ms
  - platform: monochromatic
    id: gosund_relay_status
    output: red_led
    default_transition_length: 50ms
