substitutions:
  name: gosund-dimmer
  friendly_name: Gosund Dimmer

dashboard_import:
  package_import_url: github://jimparis/esphome-provisioning/gosund-dimmer.yaml@main

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jim.gosund-dimmer
    version: "1.0"

  on_boot:
    priority: 300
    then:
      - light.turn_on: gosund_wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: gosund_wifi_status
            - delay: 500ms
      - light.turn_off: gosund_wifi_status

esp8266:
  restore_from_flash: true
  board: esp8285

# Support logging, but not to UART (since it's used by dimmer)
logger:
  baud_rate: 0

api:

ota:

external_components:
  - source:
      type: git
      url: https://github.com/jimparis/esphome-provisioning
    refresh: 1s

preferences:
  flash_write_interval: 300s

wifi:
  ap:

captive_portal:

switch:
  - platform: restart
    id: gosund_restart

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    id: button
    on_press:
      - light.toggle: gosund_light
    on_click:
      min_length: 15s
      max_length: 20s
      then:
        - switch.turn_on: gosund_restart

uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

output:
  - id: green_led
    platform: gpio
    pin: GPIO13
    inverted: true
  - id: white_led
    platform: gpio
    pin: GPIO12
    inverted: true

light:
  - name: Light
    platform: gosund
    restore_mode: RESTORE_DEFAULT_OFF
    id: gosund_light
    status_led: white_led
    default_transition_length: 0s

  - platform: binary
    id: gosund_wifi_status
    output: green_led
    restore_mode: ALWAYS_ON

# Expose ESPHome version and wifi connection info
text_sensor:
  - platform: version
    name: ESPHome Version

  - platform: wifi_info
    ip_address:
      name: IP Address
    ssid:
      name: SSID
    bssid:
      name: BSSID

# Expose uptime and wifi signal strength
sensor:
  - platform: uptime
    name: Uptime
    filters:
      - throttle: 300s
  - platform: wifi_signal
    name: WiFi Signal
    filters:
      - delta: 0.01
      - throttle: 300s
