substitutions:
  name: gosund-dimmer
  friendly_name: Gosund Dimmer

packages:
  deviceinfo: !include common/deviceinfo.yaml
  factoryreset: !include common/factoryreset.yaml

dashboard_import:
  package_import_url: github://jimparis/esphome-provisioning/gosund-dimmer.yaml@main

esphome:
  name: "${name}"
  friendly_name: "${friendly_name}"
  name_add_mac_suffix: true
  project:
    name: jim.gosund-dimmer
    version: "1.0"

  on_boot:
    priority: 300
    then:
      - light.turn_on: wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: wifi_status
            - delay: 500ms
      - light.turn_off: wifi_status

esp8266:
  restore_from_flash: true
  board: esp8285

# Support logging, but not to UART (since it's used by dimmer)
logger:
  baud_rate: 0

api:

ota:
  - platform: esphome

external_components:
  - source:
      type: git
      url: https://github.com/jimparis/esphome-provisioning
    refresh: 1s

preferences:
  flash_write_interval: 300s

wifi:
  ap:

captive_portal:

button:
  - platform: restart
    id: gosund_restart
  - platform: factory_reset
    id: gosund_factory_reset

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    id: !extend main_button
    on_press:
      - light.toggle: gosund_light

uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

output:
  - id: green_led
    platform: gpio
    pin: GPIO13
    inverted: true
  - id: white_led
    platform: gpio
    pin: GPIO12
    inverted: true

light:
  - name: Light
    platform: gosund
    restore_mode: RESTORE_DEFAULT_OFF
    id: gosund_light
    status_led: white_led
    default_transition_length: 0s
    gamma_correct: 1.0

  - platform: binary
    id: wifi_status
    output: green_led
    restore_mode: ALWAYS_ON
