button:
  - platform: restart
    id: esphome_restart
  - platform: factory_reset
    id: esphome_factory_reset

binary_sensor:
  - platform: gpio
    id: main_button
    on_multi_click:
    # Hold for 5s-10s to reboot.  Status LED is on during this window.
    - timing:
        - ON for at least 5s
      then:
        - light.turn_on: wifi_status
    - timing:
        - ON for at least 10s
      then:
        - light.turn_off: wifi_status
    - timing:
        - ON for 5s to 10s
      then:
        - button.press: esphome_restart
    # Hold for 25s-30s to factory reset.  Status LED is on during this window.
    - timing:
        - ON for at least 25s
      then:
        - light.turn_on: wifi_status
    - timing:
        - ON for at least 30s
      then:
        - light.turn_off: wifi_status
    - timing:
        - ON for 25s to 30s
      then:
        - button.press: esphome_factory_reset
