esphome:
  name: ${name}
  platform: ESP8266
  board: esp8285
  includes:
    - gosund/gosund_sw2_light.hpp
    - gosund/gosund_sw2_light.cpp
  name_add_mac_suffix: ${name_add_mac_suffix}
  on_boot:
    priority: 300
    then:
      - light.turn_on: ${id_name}_wifi_status
      - delay: 500ms
      - while:
          condition:
            not:
              wifi.connected
          then:
            - light.toggle: ${id_name}_wifi_status
            - delay: 500ms
      - light.turn_off: ${id_name}_wifi_status

# Disable logging via the UART
logger:
  baud_rate: 0

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
      inverted: true
    id: button
    on_press:
      - light.toggle: ${id_name}
    on_click:
      min_length: 5s
      max_length: 10s
      then:
        - switch.turn_on: ${id_name}_restart

switch:
  - platform: restart
    name: Reboot ${friendly_name}
    id: ${id_name}_restart

uart:
  id: uart_bus
  baud_rate: 115200
  tx_pin: GPIO1
  rx_pin: GPIO3

output:
  - id: green_led
    platform: gpio
    pin: GPIO13
    inverted: true
  - id: white_led
    platform: gpio
    pin: GPIO12
    inverted: true

light:
  - platform: custom
    lambda: |-
      auto light_out = new gosund::GosundLight(id(white_led));
      App.register_component(light_out);
      return {light_out};
    lights:
      - name: ${friendly_name}
        id: ${id_name}
        gamma_correct: 1.0
        default_transition_length: 0s
  - platform: binary
    id: ${id_name}_wifi_status
    output: green_led
    restore_mode: ALWAYS_ON

text_sensor:
# Expose ESPHome version as sensor.
  - platform: version
    name: ${friendly_name} ESPHome Version

  - platform: wifi_info
    ip_address:
      name: ${friendly_name} IP Address
    ssid:
      name: ${friendly_name} SSID
    bssid:
      name: ${friendly_name} BSSID

sensor:
# Uptime sensor.
  - platform: uptime
    name: ${friendly_name} Uptime
    filters:
      - throttle: 300s
# WiFi Signal sensor.
  - platform: wifi_signal
    name: ${friendly_name} WiFi Signal
    filters:
      - delta: 0.01
      - throttle: 300s

web_server:
  port: 80
